<?php

namespace App\Http\Controllers;

use App\Models\RekamMedis;
use Illuminate\Http\Request;

class RekamMedisController extends Controller
{
    public function index()
    {
        $data = RekamMedis::latest()->get();
        $role = auth()->user()->role;
        return view("{$role}.rekam_medis", compact('data'));
    }

    public function store(Request $request)
    {
        $request->validate([
            'no_rm' => 'required|unique:rekam_medis',
            'nama_pasien' => 'required',
            'tanggal_lahir' => 'required|date',
            'jenis_kelamin' => 'required|in:L,P',
        ]);

        RekamMedis::create($request->all());

        return back()->with('success', 'Data rekam medis berhasil ditambahkan!');
    }

    public function update(Request $request, RekamMedis $rekam_medi) // Parameter name generated by laravel for rekam-medis resource is usually rekam_medi or rekam_medis. Wait, let's just use $id.
    {
        // Let's use generic id to avoid param name mismatch
        $rm = RekamMedis::findOrFail($request->id);
        
        $request->validate([
            'no_rm' => 'required|unique:rekam_medis,no_rm,' . $rm->id,
            'nama_pasien' => 'required',
            'tanggal_lahir' => 'required|date',
            'jenis_kelamin' => 'required|in:L,P',
        ]);

        $rm->update($request->all());

        return back()->with('success', 'Data rekam medis berhasil diperbarui!');
    }

    public function validasi(Request $request, $id)
    {
        $rm = RekamMedis::findOrFail($id);
        $rm->update(['status_validasi' => $request->status_validasi]);
        return back()->with('success', 'Status validasi berhasil diperbarui!');
    }

    public function destroy($id)
    {
        RekamMedis::findOrFail($id)->delete();
        return back()->with('success', 'Data rekam medis berhasil dihapus!');
    }
}
